---
- name: Configure Nginx as a reverse proxy.
  hosts: proxy_nginx
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml
      tags:
        - install
        - update
        - configuration
        - new_site

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml
      tags:
        - install
        - update
        - configuration
        - new_site

  tasks:
    - name: Setup Nginx.
      ansible.builtin.import_tasks: tasks/nginx.yml

    - name: Setup SSL Certificates.
      ansible.builtin.import_tasks: tasks/configure-certificates.yml
      notify: Restart nginx
      tags:
        - configuration
        - ssl
        - certificate

    - name: Configure Sites
      ansible.builtin.import_tasks: tasks/nginx-sites.yml
      notify: Ensure Nginx service is running
      tags:
        - install
        - update
        - configuration
        - new_site
